### ISSUE TITLE
Python error on Linux when trying to use a plando file

### ISSUE THREAD

**Issue by geekley** [ssrando/ssrando#444]
SSRando `v1.4.1` git tag; Kubuntu 23.04; Python 3.11.2
`./ssrando.sh --placement-file /path/to/my.ssplando.json`
```
Traceback (most recent call last):
  File "/[...]/ssrando/randoscript.py", line 189, in <module>
    main()
  File "/[...]/ssrando/randoscript.py", line 120, in main
    plcmt_file.check_valid()
TypeError: PlacementFile.check_valid() missing 1 required positional argument: 'areas'
```
It's saying [check_valid](https://github.com/ssrando/ssrando/blob/v1.4.1/logic/placement_file.py#L69) method is not being passed a required `areas` argument. So it doesn't seem to be a problem with my plando file I think, since the method really is [being called](https://github.com/ssrando/ssrando/blob/v1.4.1/randoscript.py#L120) with no arguments other than self: `plcmt_file.check_valid()`.

Or am I using this placement file or command line wrong? How should I use it?
I copied it from a previous generation from the GUI, but removed most key/value pairs except top-level keys, and adjusted the things I wanted.

**Comment by geekley** [comment]
Btw it would be better if we could set plando file already on GUI (without needing keys like settings hash, permalink, etc on the json), so it would override the GUI settings.

**Comment by lepelog** [comment]
Created a fix, this feature is intentionally not on the UI because it's not really supported (as you can see, it has been broken for a while and nobody realized it). I also don't think this "placement file" is a good way of implementing a plando, but that's a separate discussion, and currently it's all we have.

**Comment by geekley** [comment]
@lepelog I tried using this placement file on v2.0.0, but I don't understand. First it requires pretty much all keys to be set in the JSON. Weird but okay ...? But then I get error like:
`logic.placement_file.InvalidPlacementFile: Missing Checks:`
This error makes me think that it's expecting me to set ***everything***! If so, then what's even the point? I can't change the file after generation without getting spoilers for that seed!

I was expecting it to work like in OoT Plando, where I set ***only some*** things on the JSON and the randomizer fills everything else that I didn't set (prioritizing the plando over the randomized settings). That's the point of a plando, otherwise it's mostly useless ...

For example: I want to set the Triforce pieces as the silent realm rewards. I want to set swords at dungeon end checks with 1 exception, etc. A well-implemented plando logic should give me the greatest freedom to set any exceptions to the randomizer.

**Comment by CovenEsme** [comment]
This basic plando support was added early into the development of SSR and was made before many of the settings we have today. Adding "proper" plando support is on the list of things to do (and lepe has done quite a lot of the groundwork for it). This is more of a temporary thing that's managed to stick around ^^'

To be completely honest, I'm surprised it works at all since the underlying logic system has completely changed since the plando file support was added
